image:
  file: .gitpod.Dockerfile
tasks:
  - before: |
      echo "This runs first, in pre-build"
    init: |
      echo "This runs in pre-build"
    command: |
      echo "This runs on each workspace start"
  - init: |
      echo "Sleeping... Long pre-build task"
      sleep 5s
      echo "Done sleeping!"
github:
  prebuilds:
    branches: true
    addCheck: prevent-merge-on-error
    addBadge: true
    addLabel: true
